# Generated by Django 3.0.8 on 2020-09-14 05:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200913_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 14, 5, 54, 59, 445710, tzinfo=utc)),
        ),
    ]
