# Generated by Django 3.0.8 on 2020-09-14 06:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200914_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default=' ', max_length=100, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 14, 6, 2, 35, 955647, tzinfo=utc)),
        ),
    ]
