# Generated by Django 3.0.8 on 2020-09-14 06:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200914_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 14, 6, 2, 41, 725252, tzinfo=utc)),
        ),
    ]
