# Generated by Django 3.0.8 on 2020-09-14 06:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200914_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 14, 6, 28, 17, 18312, tzinfo=utc)),
        ),
    ]
