# Generated by Django 3.0.8 on 2020-09-20 10:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200919_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 20, 10, 59, 14, 962478, tzinfo=utc)),
        ),
    ]
