# Generated by Django 3.0.8 on 2020-09-20 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200920_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 20, 14, 13, 28, 14239, tzinfo=utc)),
        ),
    ]
